[package]
name = "scroll-fix"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "2.1.0"
enigo = "0.2.1"
input = "0.9.0"
inputbot = "0.6.0"
libc = "0.2.158"
rdev = "0.5.3"
x11 = "2.21.0"
